### ISSUE TITLE
Use concrete Cartesian product in solve

### ISSUE THREAD

**Issue by schillic** [JuliaReach/ClosedLoopReachability.jl#171]
https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/d328a21a6a0fda136036e255b6e8a806951c1802/src/solve.jl#L134-L137

If `P₀` and `U₀` are `AbstractZonotope`s, we can use `cartesian_product` here. But that fails with a `LinearAlgebra.SingularException(5)` in `_overapproximate_hparallelotope`.

**Comment by mforets** [comment]
This issue seems outdated. We have [new defaults](https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/master/src/Algorithms/TMJets/common.jl#L44) to handle cases like this (although parallelotopes can still be preferable in some cases, but by default, it uses a reduction to order 1. We may try reduction to order 2 though, or other ways to construct a parallelotope).
